investing:
  com:
    src: "https://sbcharts.investing.com/events_charts/us"

springdoc:
  swagger-ui:
    path:"/swagger"

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/dev
    username: joonhee
    password: 1234

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 1000