server:
  port: 8080
  tomcat:
    threads:
      max: 200
    accept-count: 50

investing:
  url: "https://sbcharts.investing.com/events_charts/us"
  connectTimeout: 3000
  readTimeout: 10000

springdoc:
  swagger-ui:
    path: /swagger

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:13306/dev
    username: joonhee
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 58000
      data-source-properties:
        socketTimeout: 15000
      maximum-pool-size: 10

logging:
  level:
    root: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      max-lifetime: 58000
      data-source-properties:
        socketTimeout: 120
      maximum-pool-size: 200

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false