server:
  port: 8080
  tomcat:
    threads:
      max: 200
    accept-count: 50

investing:
  com:
    src: "https://sbcharts.investing.com/events_charts/us"

springdoc:
  swagger-ui:
    path:"/swagger"

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/dev
    username: joonhee
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 58000
#      data-source-properties:
#        socketTimeout: 30

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 10000

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false